/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Vexis API
 * API for VexisApp
 * OpenAPI spec version: 1.0
 */

export interface AgreementResponseDto {
  readonly acceptedAt: string
  readonly id: number
  readonly termsId: number
  readonly userId: number
}
