/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Vexis API
 * API for VexisApp
 * OpenAPI spec version: 1.0
 */
import type { BasicAppointmentTypeResponseDto } from './basicAppointmentTypeResponseDto'

export interface AppointmentTypeResponseDto {
  readonly appointmentType: BasicAppointmentTypeResponseDto
  readonly appointmentTypeId: number
  readonly defaultDuration: number
  readonly id: number
  readonly specialtyId: number
}
