/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Vexis API
 * API for VexisApp
 * OpenAPI spec version: 1.0
 */

export type AvailabilityControllerSearchAvailableProviderParams = {
  /**
   * The ID of the specialty to filter by
   */
  specialtyId?: number
  /**
   * Start date for the query range
   */
  startDate: string
  /**
   * End date for the query range
   */
  endDate: string
}
