/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Vexis API
 * API for VexisApp
 * OpenAPI spec version: 1.0
 */

export interface AvailabilityIntervalRequestDto {
  /** The day of the week for the working interval */
  dayOfWeek: string
  /** End time for the working interval */
  endTime: string
  /** Start time for the working interval */
  startTime: string
}
