/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Vexis API
 * API for VexisApp
 * OpenAPI spec version: 1.0
 */

export type FindScheduleResponseDtoAvailabilities = { [key: string]: unknown }
