/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Vexis API
 * API for VexisApp
 * OpenAPI spec version: 1.0
 */
import type { HealthControllerCheck200Details } from './healthControllerCheck200Details'
import type { HealthControllerCheck200Error } from './healthControllerCheck200Error'
import type { HealthControllerCheck200Info } from './healthControllerCheck200Info'

export type HealthControllerCheck200 = {
  details?: HealthControllerCheck200Details
  /** @nullable */
  error?: HealthControllerCheck200Error
  /** @nullable */
  info?: HealthControllerCheck200Info
  status?: string
}
