/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Vexis API
 * API for VexisApp
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type HealthControllerCheck200Error = {
  [key: string]: {
    status: string
    [key: string]: unknown
  }
} | null
