/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Vexis API
 * API for VexisApp
 * OpenAPI spec version: 1.0
 */

export interface HealthCouncilResponseDto {
  readonly abbreviation: string
  readonly example: string
  readonly id: number
  readonly name: string
  readonly professional: string
  readonly providerTypeIds: readonly number[]
}
