/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Vexis API
 * API for VexisApp
 * OpenAPI spec version: 1.0
 */
import type { HealthControllerCheck503Details } from './healthControllerCheck503Details'
import type { HealthControllerCheck503Error } from './healthControllerCheck503Error'
import type { HealthControllerCheck503Info } from './healthControllerCheck503Info'

export type HealthControllerCheck503 = {
  details?: HealthControllerCheck503Details
  /** @nullable */
  error?: HealthControllerCheck503Error
  /** @nullable */
  info?: HealthControllerCheck503Info
  status?: string
}
