/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Vexis API
 * API for VexisApp
 * OpenAPI spec version: 1.0
 */
import type { LoginResponseDtoRole } from './loginResponseDtoRole'

export interface LoginResponseDto {
  cpf: string
  email: string
  fullName: string
  id: number
  role: LoginResponseDtoRole
}
