/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Vexis API
 * API for VexisApp
 * OpenAPI spec version: 1.0
 */

export interface LoginRequestDto {
  /** User email address */
  email: string
  /**
   * User password
   * @minLength 8
   */
  password: string
}
