/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Vexis API
 * API for VexisApp
 * OpenAPI spec version: 1.0
 */

export type PatientProfileResponseDtoRole =
  (typeof PatientProfileResponseDtoRole)[keyof typeof PatientProfileResponseDtoRole]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatientProfileResponseDtoRole = {
  USER: 'USER',
  PROVIDER: 'PROVIDER',
  ADMIN: 'ADMIN',
  PATIENT: 'PATIENT',
} as const
