/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Vexis API
 * API for VexisApp
 * OpenAPI spec version: 1.0
 */
import type { SpecialtyResponseDto } from './specialtyResponseDto'

export interface PatientAppointmentResponseDto {
  readonly appointmentReason: string
  readonly date: string
  readonly id: number
  readonly patientId: number
  readonly providerId: number
  readonly providerName: string
  readonly specialty: SpecialtyResponseDto
  readonly startTime: string
}
