/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Vexis API
 * API for VexisApp
 * OpenAPI spec version: 1.0
 */
import type { ProviderTypeDto } from './providerTypeDto'
import type { SpecialtyDto } from './specialtyDto'

export interface ProfessionDto {
  readonly councilNumber: string
  readonly id: number
  readonly providerType: ProviderTypeDto
  readonly rqe: number
  readonly specialties: readonly SpecialtyDto[]
  readonly uf: string
}
