/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Vexis API
 * API for VexisApp
 * OpenAPI spec version: 1.0
 */
import type { SpecificProviderAvailabilitySlotDto } from './specificProviderAvailabilitySlotDto'

export interface ProviderAvailabilityResponseDto {
  readonly availableSlots: readonly SpecificProviderAvailabilitySlotDto[]
  readonly providerAvatarUrl: string
  readonly providerId: number
  readonly providerName: string
}
