/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Vexis API
 * API for VexisApp
 * OpenAPI spec version: 1.0
 */
import type { ProviderProfessionResponseDto } from './providerProfessionResponseDto'

export interface ProviderResponseDto {
  readonly appointments: readonly string[]
  readonly fullName: string
  readonly id: number
  readonly professions: readonly ProviderProfessionResponseDto[]
  readonly userId: number
}
