/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Vexis API
 * API for VexisApp
 * OpenAPI spec version: 1.0
 */

export type ProviderControllerSearchParams = {
  /**
   * Nome do provedor para filtrar
   */
  name?: string
  /**
   * ID da especialidade para filtrar
   */
  specialtyId?: number
  /**
   * Página de resultados
   */
  page?: number
}
