/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Vexis API
 * API for VexisApp
 * OpenAPI spec version: 1.0
 */
import type { SpecialtyResponseDto } from './specialtyResponseDto'

export interface ProviderAppointmentResponseDto {
  readonly date: string
  readonly id: number
  readonly patientAvatarUrl: string
  readonly patientId: number
  readonly patientName: string
  readonly specialty: SpecialtyResponseDto
  readonly startTime: string
}
