/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Vexis API
 * API for VexisApp
 * OpenAPI spec version: 1.0
 */

export interface RegisterPatientRequestDto {
  /** User CPF (unique tax identification number) */
  cpf: string
  /** User email address */
  email: string
  /** Full name of the user */
  fullName: string
  /** User password */
  password: string
  /** User phone number */
  phone: string
}
