/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Vexis API
 * API for VexisApp
 * OpenAPI spec version: 1.0
 */

export interface RegisterPatientResponseDto {
  readonly cpf: string
  readonly email: string
  readonly fullName: string
  readonly patientId: number
  readonly phone: string
  readonly userId: number
}
