/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Vexis API
 * API for VexisApp
 * OpenAPI spec version: 1.0
 */
import type { ProviderTypeResponseDto } from './providerTypeResponseDto'
import type { SpecialtyResponseDto } from './specialtyResponseDto'
import type { RegisterProviderResponseDtoUf } from './registerProviderResponseDtoUf'

export interface RegisterProviderResponseDto {
  readonly councilNumber: string
  readonly cpf: string
  readonly createdAt: string
  readonly email: string
  readonly fullName: string
  readonly id: number
  readonly phone: string
  readonly providerType: ProviderTypeResponseDto
  readonly providerTypeId: number
  readonly rqe: number
  readonly specialties: readonly SpecialtyResponseDto[]
  readonly uf: RegisterProviderResponseDtoUf
  readonly updatedAt: string
  readonly userId: number
}
