/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Vexis API
 * API for VexisApp
 * OpenAPI spec version: 1.0
 */
import type { RegisterProviderRequestDtoUf } from './registerProviderRequestDtoUf'

export interface RegisterProviderRequestDto {
  /** Provider council number */
  councilNumber: string
  /** User CPF (unique tax identification number) */
  cpf: string
  /** User email address */
  email: string
  /** Full name of the user */
  fullName: string
  /** User password */
  password: string
  /** User phone number */
  phone: string
  /** Provider type ID */
  providerTypeId: number
  /** Optional RQE number */
  rqe?: number
  /** List of specialties IDs */
  specialties: number[]
  /** Provider state abbreviation */
  uf: RegisterProviderRequestDtoUf
}
