/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Vexis API
 * API for VexisApp
 * OpenAPI spec version: 1.0
 */

export interface SearchProviderResponseDto {
  readonly fullName: string
  readonly id: number
  readonly userId: number
}
