/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Vexis API
 * API for VexisApp
 * OpenAPI spec version: 1.0
 */

export interface SocialRegisterPatientRequestDto {
  /** User CPF (unique tax identification number) */
  cpf: string
  firebaseIdToken: string
  /** Full name of the user */
  fullName: string
  /** User phone number */
  phone: string
}
