/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Vexis API
 * API for VexisApp
 * OpenAPI spec version: 1.0
 */
import type { ProviderTypeResponseDto } from './providerTypeResponseDto'

export interface SpecialtyWithProviderResponseDto {
  readonly id: number
  readonly name: string
  readonly providerType: ProviderTypeResponseDto
}
