/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Vexis API
 * API for VexisApp
 * OpenAPI spec version: 1.0
 */
import type { SpecialtyResponseDto } from './specialtyResponseDto'

export interface SpecificProviderAvailabilitySlotDto {
  readonly date: string
  readonly scheduleId: number
  readonly specialty: SpecialtyResponseDto
  readonly time: readonly string[]
}
