/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Vexis API
 * API for VexisApp
 * OpenAPI spec version: 1.0
 */
import type { AvailabilityIntervalRequestDto } from './availabilityIntervalRequestDto'

export interface UpdateScheduleRequestDto {
  /** Interval time between appointments in minutes */
  appointmentInterval: number
  /** List of IDs of the appointment types associated with the schedule */
  appointmentTypes: string[]
  /** Duration of each appointment in minutes */
  durationTime: number
  /** List of intervals for availability */
  intervals: AvailabilityIntervalRequestDto[]
}
